apiVersion: apps/v1
kind: Deployment
metadata:
  name: tee-node-pdf2image
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tee-node-pdf2image
  template:
    metadata:
      labels:
        app: tee-node-pdf2image
    spec:
      containers:
      - name: app
        image: tee-node-pdf2image:v2
        imagePullPolicy: Never 
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: converted
          mountPath: /app/converted
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: uploads
        emptyDir: {}
      - name: converted
        emptyDir: {}
      securityContext:
        runAsUser: 1000
        fsGroup: 1000