apiVersion: v1
kind: Service
metadata:
  name: tee-node-pdf2image-service
spec:
  selector:
    app: tee-node-pdf2image
  ports:
    - name: http
      protocol: TCP
      port: 80          
      targetPort: 3000  
  type: LoadBalancer
  externalTrafficPolicy: Local